/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Person me = new Person();
        Mobile myIphone = new IPhone();
        Mobile myAndroid = new Android();
        Mobile myGenericMobile = new Mobile();
        IPhoneRobot iPhoneRobot = new IPhoneRobot();




        myIphone.setBrand("iPhone");
        myIphone.setColor("Blue");
        myIphone.setName("XS");

        me.setMobile(myIphone);
        me.makeCall("testing");
        myIphone.basicInfo();

        me.setMobile(myGenericMobile);
        me.makeCall("Test");

        myAndroid.setBrand("Samsung");
        myAndroid.setName("S10");
        myAndroid.setColor("Red");

        me.setMobile(myAndroid);
        me.makeCall("teststststsststs");
        myAndroid.basicInfo();

        iPhoneRobot.setMobileOfRobot(new Android());
        iPhoneRobot.useMobile();
        iPhoneRobot.setMobileOfRobot(new IPhone());
        iPhoneRobot.useMobile();

    }
}
