/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
//    @Test public void testAppHasAGreeting() {
//        App classUnderTest = new App();
//        Person newPerson = new Person();
//
//        newPerson.makeCall("jlfklflasd;klfajkldfjakldfjklasjfdklasjdfklsjadfkla");
//    }
}
